<!-- ADP 聊天布局主组件，支持 API 模式和 Props 模式 -->
<script setup lang="ts">
import {
  ref,
  computed,
  onMounted,
  onUnmounted,
  watch,
  nextTick,
  toRefs,
  provide,
} from "vue";
import {
  Layout as TLayout,
  Content as TContent,
  MessagePlugin,
  Tooltip,
  Icon as TIcon,
} from "tdesign-vue-next";

// TLayout, TContent 已导入，模板中使用对应组件
import MainLayout from "./MainLayout.vue";
import SideLayout from "./SideLayout.vue";
import FilePreviewLayout from "./FilePreviewLayout.vue";
import LogoArea from "../LogoArea.vue";
import CustomizedIcon from "../CustomizedIcon.vue";
import type { Application, AppPattern } from "../../model/application";
import type {
  ChatConversation,
  Record,
  Reference,
  SseEvent,
  Content,
} from "../../model/chat-v2";
import type { FileProps } from "../../model/file";
import { ScoreValue } from "../../model/chat-v2";
import type { ApiConfig } from "../../service/api";
import {
  fetchApplicationList,
  fetchConversationList,
  fetchConversationDetail,
  fetchReferenceDetails,
  sendMessage,
  rateMessage,
  createShare,
  fetchUserInfo,
  uploadFile,
  parseFile,
  fetchSystemConfig,
} from "../../service/api";
import type { SystemConfig } from "../../service/api";
import { MessageCode } from "../../model/messages";
import { fetchSSE } from "../../model/sseRequest-reasoning";
import { applySseEventToRecord } from "../../utils/mergeRecord-v2";
import { hydrateType2References } from "../../utils/reference";
import { copyToClipboard } from "../../utils/clipboard";
import { useApiConfig } from "../../composables";
import { computeIsMobile } from "../../utils/device";
import {
  handleWidgetEvent as routeWidgetEvent,
  disableWidgetsByRecordId,
} from "../../widget";
import type { WidgetActionRequest } from "../../widget";
import type {
  LanguageOption,
  UserInfo,
  SideI18n,
  ChatI18n,
  ChatItemI18n,
  SenderI18n,
  FilePreviewI18n,
  ThemeProps,
  OverlayProps,
  ChatMode,
  ChatbotConfig,
} from "../../model/type";
import {
  defaultLanguageOptions,
  themePropsDefaults,
  overlayPropsDefaults,
  defaultFilePreviewI18n,
  defaultFilePreviewI18nEn,
  defaultChatI18n,
  defaultChatI18nEn,
  defaultChatItemI18n,
  defaultChatItemI18nEn,
  defaultSenderI18n,
  defaultSenderI18nEn,
} from "../../model/type";

const DEFAULT_AI_WARNING_TEXT_ZH = "内容由AI生成，仅供参考";
const DEFAULT_AI_WARNING_TEXT_EN =
  "Content is generated by AI and is for reference only";
const defaultFilePreviewI18nZhHk: Required<FilePreviewI18n> = {
  ...defaultFilePreviewI18n,
  docList: "文件列表",
  refresh: "重新整理",
  loading: "載入中...",
  loadingPreview: "正在載入文件預覽...",
  previewFailed: "預覽載入失敗",
  retry: "重試",
  openFileList: "展開工作區",
  showDocList: "顯示文件列表",
  hideDocList: "隱藏文件列表",
  unsupported: "暫不支援預覽此文件格式",
  download: "下載",
  downloadStarted: "開始下載: {name}",
};

export interface Props extends ThemeProps, OverlayProps {
  /** 当前语言标识，用于自动选择内部默认 i18n（如 'en'、'zh-HK'、'zh_CN'） */
  language?: string;
  /** 聊天模式：claw-简化模式（无文件预览/无解析进度），standard-标准模式 */
  mode?: ChatMode;
  /** 是否为浮层模式 */
  isOverlay?: boolean;
  /** 宽度（仅在 isOverlay 为 true 时用于计算 isMobile） */
  width?: string | number;
  /** 高度（仅在 isOverlay 为 true 时用于计算 isMobile） */
  height?: string | number;
  /** 容器选择器（仅在非 isOverlay 模式用于计算 isMobile） */
  container?: string;
  /** 侧边栏是否使用overlay模式 */
  isSidePanelOverlay?: boolean;
  /** 应用列表 */
  applications?: Application[];
  /** 当前选中的应用 */
  currentApplication?: Application;
  /** 当前选中的应用 ID（优先级高于 currentApplication） */
  currentApplicationId?: string;
  /** 会话列表 */
  conversations?: ChatConversation[];
  /** 当前选中的会话 */
  currentConversation?: ChatConversation;
  /** 当前选中的会话 ID（优先级高于 currentConversation） */
  currentConversationId?: string;
  /** 聊天消息列表 */
  chatList?: Record[];
  /** 是否正在聊天中 */
  isChatting?: boolean;
  /** 用户信息 */
  user?: UserInfo;
  /** 语言选项列表 */
  languageOptions?: LanguageOption[];
  /** Logo URL */
  logoUrl?: string;
  /** Logo 标题 */
  logoTitle?: string;
  /** 最大应用显示数量 */
  maxAppLen?: number;
  /** 是否显示关闭按钮 */
  showCloseButton?: boolean;
  /** AI警告文本 */
  aiWarningText?: string;
  /** 侧边栏国际化文本 */
  sideI18n?: SideI18n;
  /** 聊天国际化文本 */
  chatI18n?: ChatI18n;
  /** ChatItem 国际化文本 */
  chatItemI18n?: ChatItemI18n;
  /** Sender 国际化文本 */
  senderI18n?: SenderI18n;
  /** 是否启用语音输入 */
  enableVoiceInput?: boolean;
  /** 是否启用文件上传入口 */
  enableFileUpload?: boolean;
  /** 文件预览面板国际化文本 */
  filePreviewI18n?: FilePreviewI18n;
  /** API 配置 - 如果传入则使用 HTTP 请求获取数据 */
  apiConfig?: ApiConfig;
  /** 是否自动加载数据（仅在使用 apiConfig 时生效） */
  autoLoad?: boolean;
  /** Frontend-only POC mode: skips backend loading and uses local mock chat behavior */
  frontendPocMode?: boolean;
  /** Public chatbot config contract for fixture/API-driven UI */
  chatbotConfig?: ChatbotConfig;
}

const props = withDefaults(defineProps<Props>(), {
  ...themePropsDefaults,
  ...overlayPropsDefaults,
  language: "zh-HK",
  mode: "standard",
  isOverlay: false,
  width: 0,
  height: 0,
  container: "body",
  isSidePanelOverlay: true,
  applications: () => [],
  currentApplicationId: "",
  conversations: () => [],
  currentConversationId: "",
  chatList: () => [],
  isChatting: false,
  user: () => ({}),
  languageOptions: () => defaultLanguageOptions,
  logoUrl: "",
  logoTitle: "",
  maxAppLen: 4,
  showCloseButton: true,
  aiWarningText: DEFAULT_AI_WARNING_TEXT_ZH,
  enableVoiceInput: false,
  enableFileUpload: false,
  apiConfig: () => ({}),
  autoLoad: true,
  frontendPocMode: false,
});

const emit = defineEmits<{
  (e: "selectApplication", app: Application): void;
  (e: "selectConversation", conversation: ChatConversation): void;
  (e: "createConversation"): void;
  (e: "toggleTheme"): void;
  (e: "changeLanguage", key: string): void;
  (e: "logout"): void;
  (e: "userClick"): void;
  (e: "minimize"): void;
  (e: "close"): void;
  (e: "overlay", isOverlay: boolean): void;
  (
    e: "send",
    query: string,
    fileList: FileProps[],
    conversationId: string,
    applicationId: string,
  ): void;
  (e: "stop"): void;
  (e: "loadMore", conversationId: string, lastRecordId: string): void;
  (
    e: "rate",
    conversationId: string,
    recordId: string,
    score: (typeof ScoreValue)[keyof typeof ScoreValue],
  ): void;
  (
    e: "share",
    conversationId: string,
    applicationId: string,
    recordIds: string[],
  ): void;
  (
    e: "copy",
    rowtext: string | undefined,
    content: string | undefined,
    type: string,
  ): void;
  (e: "uploadFile", files: File[]): void;
  (e: "uploadStatus", status: "uploading" | "done"): void;
  (e: "startRecord"): void;
  (e: "stopRecord"): void;
  (e: "message", code: MessageCode, message: string): void;
  (e: "conversationChange", conversationId: string): void;
  (
    e: "dataLoaded",
    type:
      | "applications"
      | "conversations"
      | "chatList"
      | "user"
      | "systemConfig",
    data: any,
  ): void;
  /** Widget 事件（用于与 SSE/对话流交互） */
  (
    e: "widgetEvent",
    event: CustomEvent,
    widgetRunId: string,
    widgetId: string,
    recordId: string,
  ): void;
}>();

// 解构 props 保持响应式
const { theme } = toRefs(props);

const sidebarVisible = ref(!props.isSidePanelOverlay);
const mainLayoutRef = ref<InstanceType<typeof MainLayout> | null>(null);
const filePreviewLayoutRef = ref<InstanceType<typeof FilePreviewLayout> | null>(
  null,
);
const TERMS_ACCEPTED_STORAGE_PREFIX = "adp_chat_terms_accepted";
const actualLanguageValue = computed(
  () => props.language || props.chatbotConfig?.language || "zh-HK",
);
const normalizeContentLanguage = (
  language: string | undefined,
): "en" | "zh-HK" | "zh_CN" | null => {
  const value = String(language || "").trim().toLowerCase().replace(/_/g, "-");
  if (!value) return null;
  if (value.startsWith("en")) return "en";
  if (value === "zh-cn" || value === "zh-hans") return "zh_CN";
  if (value === "zh-hk" || value === "zh-hant") return "zh-HK";
  if (value.startsWith("zh")) return "zh-HK";
  return null;
};
const activeChatbotConfig = computed(() => {
  const configLanguage = normalizeContentLanguage(props.chatbotConfig?.language);
  const activeLanguage = normalizeContentLanguage(actualLanguageValue.value);
  if (!props.chatbotConfig) return undefined;
  if (!configLanguage || !activeLanguage || configLanguage === activeLanguage) {
    return props.chatbotConfig;
  }
  return undefined;
});
const backendLanguage = computed(() => {
  const value = String(actualLanguageValue.value || "")
    .trim()
    .toLowerCase()
    .replace(/_/g, "-");
  if (value.startsWith("en")) return "en-US";
  if (value === "zh-cn" || value === "zh-hans") return "zh_CN";
  if (value === "zh-hk" || value === "zh-hant") return "zh-HK";
  if (value.startsWith("zh")) return "zh-HK";
  return actualLanguageValue.value || "zh-HK";
});
const languageCustomVariables = computed(() => ({
  language: backendLanguage.value,
  locale: backendLanguage.value,
}));
const isEnglish = computed(() => actualLanguageValue.value?.startsWith("en"));
const isSimplifiedChinese = computed(
  () => normalizeContentLanguage(actualLanguageValue.value) === "zh_CN",
);
const defaultApplicationName = computed(
  () =>
    activeChatbotConfig.value?.assistant.name ||
    (isEnglish.value ? "Assistant" : "助手"),
);
const actualAiWarningText = computed(() => {
  if (props.aiWarningText === DEFAULT_AI_WARNING_TEXT_ZH && isEnglish.value) {
    return DEFAULT_AI_WARNING_TEXT_EN;
  }
  return props.aiWarningText;
});
const acceptTermsFirstMessage = computed(
  () =>
    activeChatbotConfig.value?.composer.disabledPlaceholder ||
    (isEnglish.value
      ? "Please accept the terms and conditions to continue using the chatbot."
      : "請先接受條款與細則後繼續使用。"),
);

const termsGateEnabled = computed(
  () =>
    activeChatbotConfig.value?.features.termsGate !== false &&
    activeChatbotConfig.value?.terms.enabled !== false,
);

const mockChatEnabled = computed(
  () =>
    props.frontendPocMode &&
    activeChatbotConfig.value?.features.mockChat !== false,
);

const configApplication = computed<Application | undefined>(() => {
  if (!props.frontendPocMode) return undefined;

  const config = activeChatbotConfig.value;
  if (!config) return undefined;

  return {
    ApplicationId: config.appId,
    Name: config.assistant.headerTitle || config.assistant.name,
    Avatar: config.assistant.messageAvatarUrl,
    Greeting: config.assistant.greeting,
    OpeningQuestions: [],
    Pattern: "standard",
  };
});

const normalizeApplicationName = (name?: string) => {
  const trimmed = name?.trim();
  if (
    !trimmed ||
    ["unknown", "unknown application"].includes(trimmed.toLowerCase())
  ) {
    return defaultApplicationName.value;
  }
  return trimmed;
};

const getStoredTermsAccepted = (storageKey: string) => {
  if (typeof window === "undefined") return false;
  return window.localStorage.getItem(storageKey) === "1";
};

const termsAccepted = ref(false);
const termsPromptKey = ref(0);
const lastAcceptedTermsStorageKey = ref("");

// 文件预览面板显示状态
const filePreviewVisible = ref(false);

/**
 * 切换文件预览面板显示
 * 打开时重置为纯文档列表状态，不保留上次预览态
 */
const toggleFilePreview = () => {
  if (filePreviewVisible.value) {
    filePreviewVisible.value = false;
  } else {
    filePreviewVisible.value = true;
    nextTick(() => {
      filePreviewLayoutRef.value?.resetToList();
    });
  }
};

/**
 * 打开文件预览面板
 */
const openFilePreview = () => {
  filePreviewVisible.value = true;
};

/**
 * 关闭文件预览面板
 */
const closeFilePreview = () => {
  filePreviewVisible.value = false;
};

/**
 * 打开文件预览并定位到指定路径（不展示文档列表列）
 */
const viewFile = (filePath: string) => {
  if (!filePath) return;
  openFilePreview();
  nextTick(() => {
    filePreviewLayoutRef.value?.setPreviewPath(filePath, { showDir: false });
  });
};

provide("viewFile", viewFile);

// 上传状态
const isUploading = ref(false);

// 合并 i18n 配置（根据 language 选择对应语言的默认值）
const mergedChatItemI18n = computed(() => {
  const defaults = isEnglish.value ? defaultChatItemI18nEn : defaultChatItemI18n;
  return { ...defaults, ...props.chatItemI18n };
});

// 合并文件预览 i18n 配置（根据 language 选择对应语言的默认值）
const mergedFilePreviewI18n = computed(() => {
  const defaults = isEnglish.value
    ? defaultFilePreviewI18nEn
    : isSimplifiedChinese.value
      ? defaultFilePreviewI18n
      : defaultFilePreviewI18nZhHk;
  return { ...defaults, ...props.filePreviewI18n };
});

// 计算是否为移动端模式（内部计算，不再依赖外部传入）
const isMobile = computed(() => {
  return computeIsMobile({
    isOverlay: props.isOverlay,
    width: props.width,
    height: props.height,
    container: props.container,
  });
});

provide("isMobile", isMobile);

// 内部数据状态（当使用 API 时）
const internalApplications = ref<Application[]>([]);
const internalConversations = ref<ChatConversation[]>([]);
const internalUser = ref<{
  avatarUrl?: string;
  avatarName?: string;
  name?: string;
}>({});
const internalCurrentApplication = ref<Application | undefined>(undefined);
const internalCurrentConversation = ref<ChatConversation | undefined>(
  undefined,
);
const applicationsResolved = ref(!props.autoLoad || props.frontendPocMode);

// 用于确保 applications 列表加载完成后再判断模式
let resolveApplicationsReady: () => void;
const applicationsReadyPromise = new Promise<void>((resolve) => {
  resolveApplicationsReady = resolve;
});

const internalSystemConfig = ref<SystemConfig>({ EnableVoiceInput: true });
const referenceDetailCache = new Map<string, Reference>();
const referenceDetailPendingKeys = new Set<string>();

interface ConversationRuntimeState {
  records: Record[];
  isChatting: boolean;
  abortController: AbortController | null;
  applicationId?: string;
}

type ConversationRuntimeStateMap = {
  [key: string]: ConversationRuntimeState;
};

const conversationRuntimeStates = ref<ConversationRuntimeStateMap>({});
const currentConversationStateKey = ref("");
let pendingConversationSeq = 0;

const createPendingConversationKey = () =>
  `pending-conversation:${Date.now()}:${pendingConversationSeq++}`;

const getConversationRuntimeState = (key: string) => {
  if (!key) {
    return undefined;
  }
  return conversationRuntimeStates.value[key];
};

const ensureConversationRuntimeState = (key: string) => {
  if (!key) {
    return undefined;
  }
  let state = conversationRuntimeStates.value[key];
  if (!state) {
    state = {
      records: [],
      isChatting: false,
      abortController: null,
    };
    conversationRuntimeStates.value[key] = state;
  }
  return state;
};

const getConversationRecords = (key: string) => {
  return getConversationRuntimeState(key)?.records ?? [];
};

const isConversationChatting = (key: string) => {
  return getConversationRuntimeState(key)?.isChatting ?? false;
};

const setConversationRecords = (
  key: string,
  records: Record[],
  applicationId?: string,
) => {
  const state = ensureConversationRuntimeState(key);
  if (!state) {
    return [];
  }
  state.records = records;
  if (applicationId) {
    state.applicationId = applicationId;
  }
  return state.records;
};

const setConversationApplicationId = (key: string, applicationId?: string) => {
  if (!key || !applicationId) {
    return;
  }
  const state = ensureConversationRuntimeState(key);
  if (!state) {
    return;
  }
  state.applicationId = applicationId;
};

const moveConversationRuntimeState = (
  fromKey: string,
  toKey: string,
  applicationId?: string,
) => {
  if (!fromKey) {
    setConversationApplicationId(toKey, applicationId);
    return toKey;
  }
  if (!toKey || fromKey === toKey) {
    setConversationApplicationId(fromKey, applicationId);
    return fromKey;
  }

  const fromState = getConversationRuntimeState(fromKey);
  if (!fromState) {
    setConversationApplicationId(toKey, applicationId);
    return toKey;
  }

  conversationRuntimeStates.value[toKey] = fromState;
  if (applicationId) {
    fromState.applicationId = applicationId;
  }
  delete conversationRuntimeStates.value[fromKey];
  return toKey;
};

const upsertConversation = (conversation: ChatConversation) => {
  if (!conversation?.Id) {
    return;
  }

  const idx = internalConversations.value.findIndex(
    (item) => item.Id === conversation.Id,
  );
  if (idx >= 0) {
    internalConversations.value.splice(idx, 1, {
      ...internalConversations.value[idx],
      ...conversation,
    });
  } else {
    internalConversations.value.unshift(conversation);
  }
};

const stopConversationStream = (key: string) => {
  const state = getConversationRuntimeState(key);
  if (!state) {
    return;
  }
  if (state.abortController) {
    state.abortController.abort();
    state.abortController = null;
  }
  state.isChatting = false;
};

// POC mode keeps the visual widget interactive without requiring backend APIs.
const useApiMode = computed(() => !props.frontendPocMode);

// 是否启用语音输入
const enableVoiceInput = computed(
  () => props.enableVoiceInput && internalSystemConfig.value.EnableVoiceInput,
);
const enableFileUpload = computed(
  () => props.enableFileUpload,
);

// 合并默认值和传入值的 chatI18n（根据 language 选择对应语言的默认值）
const mergedChatI18n = computed(() => {
  const defaults = isEnglish.value ? defaultChatI18nEn : defaultChatI18n;
  return { ...defaults, ...props.chatI18n };
});

// 合并默认值和传入值的 senderI18n（根据 language 选择对应语言的默认值）
const mergedSenderI18n = computed(() => {
  const defaults = isEnglish.value ? defaultSenderI18nEn : defaultSenderI18n;
  return { ...defaults, ...props.senderI18n };
});

// 使用 composable 统一管理 API 配置
const { mergedApiDetailConfig } = useApiConfig({
  apiConfig: computed((): ApiConfig | undefined => props.apiConfig),
});

const isStreamAbortError = (msg: unknown) => {
  return !!(
    msg &&
    typeof msg === "object" &&
    (("name" in msg && msg.name === "AbortError") ||
      ("code" in msg && msg.code === "ERR_CANCELED"))
  );
};

const markLatestAssistantError = (
  conversationKey: string,
  statusDesc: string,
) => {
  const targetState = getConversationRuntimeState(conversationKey);
  if (!targetState) {
    return;
  }
  const assistantRecord = [...targetState.records]
    .reverse()
    .find(
      (item) =>
        item.Role === "assistant" || item.RecordId === "placeholder-agent",
    );
  if (!assistantRecord) {
    return;
  }
  assistantRecord.Status = "error";
  assistantRecord.StatusDesc = statusDesc;
};

const handleStreamFailure = (msg: unknown) => {
  if (isStreamAbortError(msg)) {
    return "";
  }
  if (
    msg &&
    typeof msg === "object" &&
    "response" in msg &&
    msg.response &&
    typeof msg.response === "object"
  ) {
    const response = msg.response as { status?: number };
    if (response.status === 401) {
      const loginExpiredText = mergedChatI18n.value.loginExpired;
      MessagePlugin.error(loginExpiredText);
      emit("message", MessageCode.SEND_MESSAGE_FAILED, loginExpiredText);
      return loginExpiredText;
    }
  }
  if (
    msg &&
    typeof msg === "object" &&
    "code" in msg &&
    msg.code === "ERR_NETWORK"
  ) {
    const networkErrorText = mergedChatI18n.value.networkError;
    MessagePlugin.error(networkErrorText);
    emit("message", MessageCode.NETWORK_ERROR, networkErrorText);
    return networkErrorText;
  }
  if (typeof msg === "string") {
    MessagePlugin.error(msg);
    emit("message", MessageCode.SEND_MESSAGE_FAILED, msg);
    return msg;
  }
  const sendErrorText = mergedChatI18n.value.sendError;
  MessagePlugin.error(sendErrorText);
  emit("message", MessageCode.SEND_MESSAGE_FAILED, sendErrorText);
  return sendErrorText;
};

const hydrateReferences = async (
  records: Record[],
  options: { applicationId?: string; shareId?: string } = {},
) => {
  if (records.length === 0) {
    return;
  }

  try {
    await hydrateType2References(records, {
      ...options,
      cache: referenceDetailCache,
      pending: referenceDetailPendingKeys,
      fetcher: (params) =>
        fetchReferenceDetails(
          params,
          mergedApiDetailConfig.value.referenceDetailApi,
        ),
    });
  } catch (error) {
    console.error("补充引用切片失败:", error);
  }
};

// 实际使用的数据（优先使用 props，否则使用内部数据）
const actualApplications = computed(() =>
  props.applications.length > 0
    ? props.applications
    : configApplication.value
      ? [configApplication.value]
      : internalApplications.value,
);
const actualConversations = computed(() =>
  props.conversations.length > 0
    ? props.conversations
    : internalConversations.value,
);
const actualChatList = computed(() =>
  props.chatList.length > 0
    ? props.chatList
    : getConversationRecords(currentConversationStateKey.value),
);
const actualUser = computed(() =>
  props.user && Object.keys(props.user).length > 0
    ? props.user
    : internalUser.value,
);
const actualCurrentApplication = computed(
  () =>
    props.currentApplication ||
    configApplication.value ||
    internalCurrentApplication.value,
);
const actualCurrentConversation = computed(
  () => props.currentConversation || internalCurrentConversation.value,
);
const actualIsChatting = computed(() =>
  useApiMode.value
    ? isConversationChatting(currentConversationStateKey.value)
    : props.isChatting,
);

// 计算属性
const currentApplicationId = computed(
  () =>
    actualCurrentApplication.value?.ApplicationId ||
    props.currentApplicationId ||
    "",
);
const currentApplicationAvatar = computed(
  () => actualCurrentApplication.value?.Avatar || "",
);
const currentApplicationName = computed(() =>
  normalizeApplicationName(actualCurrentApplication.value?.Name),
);
const currentApplicationGreeting = computed(
  () => actualCurrentApplication.value?.Greeting || "",
);
const currentApplicationOpeningQuestions = computed(
  () => actualCurrentApplication.value?.OpeningQuestions || [],
);
const currentConversationId = computed(
  () =>
    props.currentConversationId || actualCurrentConversation.value?.Id || "",
);
const currentConversationTitle = computed(() => {
  const conversationId =
    currentConversationId.value || currentConversationStateKey.value;
  if (!conversationId) return "";

  const activeConversation =
    actualConversations.value.find(
      (conversation) => conversation.Id === conversationId,
    ) || actualCurrentConversation.value;

  return activeConversation?.Title?.trim() || "";
});
const currentTermsSectionKey = computed(() => {
  if (!termsGateEnabled.value) return "disabled";
  const storageScope =
    activeChatbotConfig.value?.terms.storageScope || "conversation";
  const appKey =
    activeChatbotConfig.value?.appId || currentApplicationId.value || "pending";
  if (storageScope === "global") return `global:${appKey}`;
  if (storageScope === "application") return `application:${appKey}`;
  const conversationId =
    currentConversationId.value || currentConversationStateKey.value;
  if (conversationId) return `conversation:${conversationId}`;
  if (currentApplicationId.value)
    return `application:${currentApplicationId.value}:new`;
  return "application:pending";
});
const currentTermsStorageKey = computed(
  () => `${TERMS_ACCEPTED_STORAGE_PREFIX}:${currentTermsSectionKey.value}`,
);
const termsResolving = computed(
  () =>
    currentTermsSectionKey.value === "application:pending" &&
    !applicationsResolved.value &&
    props.applications.length === 0 &&
    !props.currentApplication &&
    !props.currentApplicationId,
);

watch(
  currentTermsStorageKey,
  (newStorageKey, oldStorageKey) => {
    const shouldTransferToCreatedConversation =
      Boolean(oldStorageKey) &&
      termsAccepted.value &&
      lastAcceptedTermsStorageKey.value === oldStorageKey &&
      currentTermsSectionKey.value.startsWith("conversation:");

    if (shouldTransferToCreatedConversation) {
      if (typeof window !== "undefined") {
        window.localStorage.setItem(newStorageKey, "1");
      }
      lastAcceptedTermsStorageKey.value = newStorageKey;
      termsAccepted.value = true;
      return;
    }

    termsAccepted.value = getStoredTermsAccepted(newStorageKey);
    termsPromptKey.value += 1;
  },
  { immediate: true },
);

const handleAcceptTerms = () => {
  if (!termsGateEnabled.value) return;
  const storageKey = currentTermsStorageKey.value;
  termsAccepted.value = true;
  lastAcceptedTermsStorageKey.value = storageKey;
  if (typeof window !== "undefined") {
    window.localStorage.setItem(storageKey, "1");
  }
  nextTick(() => {
    mainLayoutRef.value?.getChatRef()?.backToBottom();
  });
};

const handleDeclineTerms = () => {
  if (!termsGateEnabled.value) return;
  const storageKey = currentTermsStorageKey.value;
  termsAccepted.value = false;
  termsPromptKey.value += 1;
  if (typeof window !== "undefined") {
    window.localStorage.removeItem(storageKey);
  }
  MessagePlugin.info(acceptTermsFirstMessage.value);
};

/**
 * 聊天模式：优先使用 props.mode 手动配置，否则从当前应用的 Pattern 自动推导
 * Pattern='ClawAgent' → mode='claw'，其他值或 null → mode='standard'
 */
const chatMode = computed<ChatMode>(() => {
  if (props.mode !== "standard") {
    return props.mode;
  }
  const pattern = actualCurrentApplication.value?.Pattern as
    | AppPattern
    | null
    | undefined;
  if (pattern === "ClawAgent") {
    return "claw";
  }
  return "standard";
});

// API 数据加载方法
const loadApplications = async () => {
  if (!useApiMode.value) {
    resolveApplicationsReady();
    return;
  }
  try {
    const data = await fetchApplicationList(
      mergedApiDetailConfig.value.applicationListApi,
    );
    internalApplications.value = data;
    // 默认选中第一个应用
    if (data.length > 0 && !internalCurrentApplication.value) {
      internalCurrentApplication.value = data[0];
    }
    emit("dataLoaded", "applications", data);
  } catch (error) {
    const text = mergedChatI18n.value.getAppListFailed;
    MessagePlugin.error(text);
    emit("message", MessageCode.GET_APP_LIST_FAILED, text);
  } finally {
    applicationsResolved.value = true;
    resolveApplicationsReady();
  }
};

const loadConversations = async () => {
  if (!useApiMode.value) return;
  try {
    const data = await fetchConversationList(
      mergedApiDetailConfig.value.conversationListApi,
    );
    internalConversations.value = data;
    emit("dataLoaded", "conversations", data);
  } catch (error) {
    const text = mergedChatI18n.value.getConversationListFailed;
    MessagePlugin.error(text);
    emit("message", MessageCode.GET_CONVERSATION_LIST_FAILED, text);
  }
};

const loadConversationDetail = async (conversationId: string) => {
  if (!useApiMode.value || !conversationId) return;
  // 确保 applications 列表已加载完成
  await applicationsReadyPromise;
  try {
    const response = await fetchConversationDetail(
      { ConversationId: conversationId },
      mergedApiDetailConfig.value.conversationDetailApi,
    );
    const records: Record[] = response?.Response?.Records || [];
    const applicationId = response?.Response?.ApplicationId || "";

    setConversationRecords(conversationId, records, applicationId);
    await hydrateReferences(records, { applicationId });
    emit("dataLoaded", "chatList", records);
  } catch (error) {
    const text = mergedChatI18n.value.getConversationDetailFailed;
    MessagePlugin.error(text);
    emit("message", MessageCode.GET_CONVERSATION_DETAIL_FAILED, text);
  }
};

const loadUserInfo = async () => {
  if (!useApiMode.value) return;
  try {
    const data = await fetchUserInfo(mergedApiDetailConfig.value.userInfoApi);
    internalUser.value = {
      avatarUrl: data.Avatar,
      avatarName: data.Name?.charAt(0) || "",
      name: data.Name,
    };
    emit("dataLoaded", "user", internalUser.value);
  } catch (error) {
    // 用户信息获取失败不影响主流程
    console.error("获取用户信息失败:", error);
  }
};

const loadSystemConfig = async () => {
  if (!useApiMode.value) return;
  try {
    const data = await fetchSystemConfig(
      mergedApiDetailConfig.value.systemConfigApi,
    );
    internalSystemConfig.value = data;
    emit("dataLoaded", "systemConfig", internalSystemConfig.value);
  } catch (error) {
    // 系统配置获取失败不影响主流程，默认不启用语音输入
    console.error("获取系统配置失败:", error);
  }
};

const fileToContent = (file: FileProps): Content | null => {
  if (file.status !== "done" || !file.url) return null;
  const extName = file.name?.split(".").pop() || "";
  return {
    Type: "file",
    File: {
      Uid: file.uid,
      DocId: file.docId || "0",
      FileName: file.name || "",
      FileUrl: file.url,
      FileSize: String(file.size || 0),
      FileType: file.type || extName,
      MimeType: file.type || "",
      LocalOnly: file.localOnly,
    },
  };
};

const getLocalAudioFile = (fileList: FileProps[]) =>
  fileList.find((file) => file.localOnly && file.category === "audio");

const getLocalAudioRecordId = (file: FileProps) => `local-audio-${file.uid}`;

const appendLocalOnlyFileContents = (
  record: Record,
  localRecord: Record | undefined,
): Record => {
  if (!localRecord?.Messages?.length) return record;
  const localContents = localRecord.Messages.flatMap((message) =>
    (message.Contents || []).filter(
      (content) => content.Type === "file" && content.File?.LocalOnly,
    ),
  );
  if (localContents.length === 0) return record;

  const messages = record.Messages ? [...record.Messages] : [];
  const messageIndex = messages.findIndex((message) => message.Type === "question");
  const targetIndex = messageIndex >= 0 ? messageIndex : 0;
  const targetMessage = messages[targetIndex];
  if (!targetMessage) return record;

  const contents = targetMessage.Contents ? [...targetMessage.Contents] : [];
  const seen = new Set(
    contents
      .filter((content) => content.Type === "file" && content.File?.LocalOnly)
      .map((content) => content.File?.Uid || content.File?.FileUrl || ""),
  );
  for (const content of localContents) {
    const key = content.File?.Uid || content.File?.FileUrl || "";
    if (key && seen.has(key)) continue;
    contents.push(content);
    if (key) seen.add(key);
  }

  messages[targetIndex] = { ...targetMessage, Contents: contents };
  return { ...record, Messages: messages };
};

const handleInternalRecordAudio = (
  file: FileProps,
  conversationId: string,
  applicationId: string,
) => {
  if (!useApiMode.value) return;

  const streamConversationKey =
    conversationId ||
    currentConversationStateKey.value ||
    createPendingConversationKey();
  currentConversationStateKey.value = streamConversationKey;
  const streamState = ensureConversationRuntimeState(streamConversationKey);
  if (!streamState) return;

  streamState.applicationId =
    applicationId ||
    streamState.applicationId ||
    internalCurrentConversation.value?.ApplicationId ||
    internalCurrentApplication.value?.ApplicationId;

  const fileContent = fileToContent(file);
  if (!fileContent) return;

  const recordId = getLocalAudioRecordId(file);
  if (streamState.records.some((record) => record.RecordId === recordId)) {
    return;
  }

  const timestamp = Date.now();
  streamState.records.push({
    Role: "user",
    RecordId: recordId,
    ConversationId: conversationId || streamConversationKey,
    Status: "success",
    StatusDesc: "",
    Messages: [
      {
        Type: "question",
        MessageId: `${recordId}-message`,
        Name: "question",
        Title: "",
        Status: "success",
        StatusDesc: "",
        Contents: [fileContent],
      },
    ],
    ExtraInfo: {
      RequestId: "",
      TraceId: "",
      Elapsed: 0,
      StartTime: timestamp,
      IsFromSelf: true,
    },
  });

  nextTick(() => {
    mainLayoutRef.value?.getChatRef()?.backToBottom();
  });
};

// 内部发送消息处理（API 模式）
const handleInternalSend = async (
  query: string,
  fileList: FileProps[],
  conversationId: string,
  applicationId: string,
) => {
  if (isUploading.value) return;
  if (!useApiMode.value) {
    if (props.frontendPocMode && mockChatEnabled.value) {
      const streamConversationKey =
        currentConversationStateKey.value || "poc-conversation";
      currentConversationStateKey.value = streamConversationKey;
      const streamState = ensureConversationRuntimeState(streamConversationKey);
      if (!streamState) return;

      const timestamp = Date.now();
      const baseExtraInfo = (isFromSelf: boolean, offset = 0) => ({
        RequestId: "",
        TraceId: "",
        Elapsed: 0,
        StartTime: timestamp + offset,
        IsFromSelf: isFromSelf,
        CanRating: false,
        CanFeedback: false,
      });
      const createTextRecord = (
        role: "assistant" | "user",
        recordId: string,
        messageType: "reply" | "question",
        text: string,
        offset = 0,
      ): Record => ({
        Role: role,
        RecordId: recordId,
        ConversationId: streamConversationKey,
        Status: "success",
        StatusDesc: "",
        Messages: [
          {
            Type: messageType,
            MessageId: `${recordId}-message`,
            Name: messageType,
            Title: "",
            Status: "success",
            StatusDesc: "",
            Contents: [{ Type: "text", Text: text }],
          },
        ],
        ExtraInfo: baseExtraInfo(role === "user", offset),
      });

      streamState.records.push(
        createTextRecord("user", `poc-user-${timestamp}`, "question", query),
        createTextRecord(
          "assistant",
          `poc-assistant-${timestamp}`,
          "reply",
          activeChatbotConfig.value?.mockChat.reply ||
            (isEnglish.value
              ? "This is a frontend POC reply. The real chatbot backend will be connected later."
              : "這是前端 POC 回覆，正式聊天功能會在後端整合階段接入。"),
          1,
        ),
      );
      nextTick(() => {
        mainLayoutRef.value?.getChatRef()?.backToBottom();
      });
      return;
    }
    if (props.frontendPocMode) {
      return;
    }
    emit("send", query, fileList, conversationId, applicationId);
    return;
  }

  let streamConversationKey =
    conversationId ||
    currentConversationStateKey.value ||
    createPendingConversationKey();
  currentConversationStateKey.value = streamConversationKey;
  const streamState = ensureConversationRuntimeState(streamConversationKey);
  if (!streamState) {
    return;
  }
  streamState.isChatting = true;
  streamState.applicationId =
    applicationId ||
    streamState.applicationId ||
    internalCurrentConversation.value?.ApplicationId ||
    internalCurrentApplication.value?.ApplicationId;
  // 重置用户滚动状态
  mainLayoutRef.value?.getChatRef()?.setHasUserScrolled(false);

  const timestamp = Date.now();
  const localAudioFile = getLocalAudioFile(fileList);
  const userPlaceholderId = localAudioFile
    ? getLocalAudioRecordId(localAudioFile)
    : "placeholder-user";
  const baseExtraInfo = (isFromSelf: boolean) => ({
    RequestId: "",
    TraceId: "",
    Elapsed: 0,
    StartTime: timestamp,
    IsFromSelf: isFromSelf,
  });

  // 构建用户消息展示内容（图片和文档都作为 file Content 展示）
  const userContents: Content[] = [{ Type: "text", Text: query }];
  for (const file of fileList) {
    const fileContent = fileToContent(file);
    if (fileContent) userContents.push(fileContent);
  }

  // 创建用户消息占位
  const userRecord: Record = {
    Role: "user",
    RecordId: userPlaceholderId,
    ConversationId: conversationId || streamConversationKey,
    Status: "success",
    StatusDesc: "",
    Messages: [
      {
        Type: "question",
        MessageId: `placeholder-user-${timestamp}`,
        Name: "question",
        Title: "",
        Status: "success",
        StatusDesc: "",
        Contents: userContents,
      },
    ],
    ExtraInfo: baseExtraInfo(true),
  };
  const existingUserRecordIndex = streamState.records.findIndex(
    (record) => record.RecordId === userPlaceholderId,
  );
  if (existingUserRecordIndex >= 0) {
    streamState.records.splice(existingUserRecordIndex, 1, userRecord);
  } else {
    streamState.records.push(userRecord);
  }

  // 创建助手消息占位
  const assistantRecord: Record = {
    Role: "assistant",
    RecordId: "placeholder-agent",
    ConversationId: conversationId || streamConversationKey,
    Status: "processing",
    StatusDesc: "",
    Messages: [],
    ExtraInfo: baseExtraInfo(false),
  };
  streamState.records.push(assistantRecord);

  // 发送消息后滚动到底部
  nextTick(() => {
    mainLayoutRef.value?.getChatRef()?.backToBottom();
  });

  streamState.abortController = new AbortController();

  const contents: Content[] = [{ Type: "text", Text: query }];
  // 将所有已上传成功的文件（图片和文档）以 file content 格式加入
  for (const file of fileList) {
    if (file.localOnly) continue;
    const fileContent = fileToContent(file);
    if (fileContent) contents.push(fileContent);
  }
  const backendFileList = fileList.filter((file) => !file.localOnly);
  await fetchSSE(
    () => {
      return sendMessage(
        {
          Contents: contents,
          ConversationId: conversationId || undefined,
          ApplicationId: applicationId,
          FileInfos: backendFileList,
          Language: backendLanguage.value,
          CustomVariables: languageCustomVariables.value,
        },
        { signal: streamState.abortController?.signal },
        mergedApiDetailConfig.value.sendMessageApi,
      );
    },
    {
      success(event: SseEvent) {
        if (event.Type === "conversation") {
          upsertConversation(event.Payload);
          // 创建新的对话，重新调用 chatlist 接口更新列表
          loadConversations();
          if (event.Payload.IsNewConversation) {
            const previousKey = streamConversationKey;
            streamConversationKey = moveConversationRuntimeState(
              previousKey,
              event.Payload.Id,
              event.Payload.ApplicationId || streamState.applicationId,
            );
            if (currentConversationStateKey.value === previousKey) {
              currentConversationStateKey.value = streamConversationKey;
            }
          }
          if (currentConversationStateKey.value === event.Payload.Id) {
            internalCurrentConversation.value = {
              ...(internalCurrentConversation.value || event.Payload),
              ...event.Payload,
            };
          }
          return;
        }

        const targetState = ensureConversationRuntimeState(
          streamConversationKey,
        );
        if (!targetState) {
          return;
        }
        const resolvedApplicationId =
          targetState.applicationId ||
          applicationId ||
          internalCurrentApplication.value?.ApplicationId;

        const replacePlaceholder = (
          placeholderId: string,
          next: Record,
        ): Record | undefined => {
          const placeholderIdx = targetState.records.findIndex(
            (item) => item.RecordId === placeholderId,
          );
          if (placeholderIdx !== -1) {
            targetState.records.splice(placeholderIdx, 1, next);
            return next;
          }
          return undefined;
        };

        const updateRecord = (next: Record, placeholderId: string): Record => {
          const idx = targetState.records.findIndex(
            (item) => item.RecordId === next.RecordId,
          );
          if (idx !== -1) {
            if (targetState.records[idx] !== undefined) {
              Object.assign(targetState.records[idx], next);
              return targetState.records[idx] as Record;
            }
            return next;
          }
          const replaced = replacePlaceholder(placeholderId, next);
          if (replaced) {
            return replaced;
          }
          targetState.records.push(next);
          return next;
        };

        if (event.Type === "request_ack") {
          // 用户消息：替换占位
          const placeholderUser = targetState.records.find(
            (item) => item.RecordId === userPlaceholderId,
          );
          const nextUser = applySseEventToRecord(event, placeholderUser);
          if (nextUser) {
            const userWithLocalAudio = appendLocalOnlyFileContents(
              nextUser,
              placeholderUser,
            );
            const appliedUser = updateRecord(userWithLocalAudio, userPlaceholderId);
            void hydrateReferences([appliedUser], {
              applicationId: resolvedApplicationId,
            });
          }
        } else {
          // 助手消息：只用占位 + lastRecord
          const lastIndex = targetState.records.length - 1;
          const lastRecord = targetState.records[lastIndex];
          const baseAssistant =
            lastRecord &&
            (lastRecord.RecordId === "placeholder-agent" ||
              lastRecord.Role === "assistant")
              ? lastRecord
              : undefined;
          const nextAssistant = applySseEventToRecord(event, baseAssistant);
          if (nextAssistant) {
            const appliedAssistant = updateRecord(
              nextAssistant,
              "placeholder-agent",
            );
            void hydrateReferences([appliedAssistant], {
              applicationId: resolvedApplicationId,
            });
          }
        }

        // 每次收到数据后滚动到底部
        if (currentConversationStateKey.value === streamConversationKey) {
          nextTick(() => {
            mainLayoutRef.value?.getChatRef()?.backToBottom();
          });
        }
      },
      complete(isOk) {
        const targetState = getConversationRuntimeState(streamConversationKey);
        if (targetState) {
          targetState.isChatting = false;
          targetState.abortController = null;
        }
        if (!isOk) {
          return;
        }
        // 完成后滚动到底部并延迟重置用户滚动状态
        if (currentConversationStateKey.value === streamConversationKey) {
          nextTick(() => {
            mainLayoutRef.value?.getChatRef()?.backToBottom();
            setTimeout(() => {
              mainLayoutRef.value?.getChatRef()?.setHasUserScrolled(false);
            }, 500);
          });
        }
      },
      fail(msg) {
        const failureText = handleStreamFailure(msg);
        if (failureText) {
          markLatestAssistantError(streamConversationKey, failureText);
        }
      },
    },
  );
};

// 内部停止处理（API 模式）
const handleInternalStop = () => {
  stopConversationStream(currentConversationStateKey.value);
  emit("stop");
};

// 内部加载更多处理（API 模式）
const handleInternalLoadMore = async (
  conversationId: string,
  lastRecordId: string,
) => {
  if (!useApiMode.value) {
    emit("loadMore", conversationId, lastRecordId);
    return;
  }

  // 确保 applications 列表已加载完成
  await applicationsReadyPromise;

  try {
    const response = await fetchConversationDetail(
      { ConversationId: conversationId, LastRecordId: lastRecordId },
      mergedApiDetailConfig.value.conversationDetailApi,
    );
    const newRecords: Record[] = response?.Response?.Records || [];
    const applicationId =
      response?.Response?.ApplicationId ||
      internalCurrentApplication.value?.ApplicationId ||
      "";

    if (newRecords.length > 0) {
      await hydrateReferences(newRecords, { applicationId });
      const targetState = ensureConversationRuntimeState(conversationId);
      if (targetState) {
        targetState.records = [...newRecords, ...targetState.records];
        if (applicationId) {
          targetState.applicationId = applicationId;
        }
      }
      mainLayoutRef.value?.notifyLoaded();
    } else {
      mainLayoutRef.value?.notifyComplete();
    }
    nextTick(() => {
      if (!lastRecordId) {
        mainLayoutRef.value?.getChatRef()?.backToBottom();
      }
    });
  } catch (error) {
    mainLayoutRef.value?.notifyComplete();
    const text = mergedChatI18n.value.loadMoreFailed;
    MessagePlugin.error(text);
    emit("message", MessageCode.LOAD_MORE_FAILED, text);
  }
};

// 内部评分处理（API 模式）
const handleInternalRate = async (
  conversationId: string,
  recordId: string,
  score: (typeof ScoreValue)[keyof typeof ScoreValue],
) => {
  if (!useApiMode.value) {
    emit("rate", conversationId, recordId, score);
    return;
  }

  try {
    await rateMessage(
      { ConversationId: conversationId, RecordId: recordId, Score: score },
      mergedApiDetailConfig.value.rateApi,
    );
    // 更新本地状态
    const record = getConversationRecords(conversationId).find(
      (r) => r.RecordId === recordId,
    );
    if (record) {
      record.Score = score;
    }
    // 显示感谢反馈信息（使用 i18n 文案）
    const message =
      score === ScoreValue.Like
        ? mergedChatItemI18n.value.thxForGood
        : score === ScoreValue.Dislike
          ? mergedChatItemI18n.value.thxForBad
          : "";
    if (message) {
      MessagePlugin.info(message);
    }
  } catch (error) {
    const text = mergedChatI18n.value.rateFailed;
    MessagePlugin.error(text);
    emit("message", MessageCode.RATE_FAILED, text);
  }
};

// 内部分享处理（API 模式）
const handleInternalShare = async (
  conversationId: string,
  applicationId: string,
  recordIds: string[],
) => {
  if (!useApiMode.value) {
    emit("share", conversationId, applicationId, recordIds);
    return;
  }

  try {
    const response = await createShare(
      {
        ConversationId: conversationId,
        ApplicationId: applicationId,
        RecordIds: recordIds,
      },
      mergedApiDetailConfig.value.shareApi,
    );
    const shareUrl = `${window.location.origin}${window.location.pathname}#/share?ShareId=${response.ShareId}`;
    await copyToClipboard(shareUrl, {
      isMobile: isMobile.value,
      onSuccess: () => {
        MessagePlugin.success(mergedChatI18n.value.copySuccess);
      },
      onError: () => {
        const text = mergedChatI18n.value.copyFailed;
        MessagePlugin.error(text);
        emit("message", MessageCode.COPY_FAILED, text);
      },
    });
  } catch (error) {
    const text = mergedChatI18n.value.shareFailed;
    MessagePlugin.error(text);
    emit("message", MessageCode.SHARE_FAILED, text);
  }
};

const handleToggleSidebar = () => {
  sidebarVisible.value = !sidebarVisible.value;
};

const handleSelectApplication = (app: Application) => {
  if (useApiMode.value) {
    internalCurrentApplication.value = app;
    internalCurrentConversation.value = undefined;
    currentConversationStateKey.value = "";
    // 清空 Sender 中的已选文件和输入内容
    const senderRef = mainLayoutRef.value?.getChatRef()?.getSenderRef();
    if (senderRef) {
      senderRef.changeSenderVal("", []);
    }
  }
  // 切换应用时关闭文件预览面板
  closeFilePreview();
  // 移动端选择应用后收起侧边栏
  if (isMobile.value || props.isSidePanelOverlay) {
    sidebarVisible.value = false;
  }
  emit("selectApplication", app);
};

const handleSelectConversation = async (conversation: ChatConversation) => {
  const isSameConversation =
    conversation.Id === internalCurrentConversation.value?.Id &&
    currentConversationStateKey.value === conversation.Id;

  if (isSameConversation) {
    if (isMobile.value) {
      sidebarVisible.value = false;
    }
    return;
  }

  if (useApiMode.value) {
    internalCurrentConversation.value = conversation;
    currentConversationStateKey.value = conversation.Id;
    setConversationApplicationId(conversation.Id, conversation.ApplicationId);
  }
  // 切换会话时关闭文件预览面板
  closeFilePreview();
  // 移动端选择对话后收起侧边栏
  if (isMobile.value) {
    sidebarVisible.value = false;
  }
  emit("selectConversation", conversation);
};

const handleCreateConversation = () => {
  if (useApiMode.value) {
    internalCurrentConversation.value = undefined;
    currentConversationStateKey.value = "";
  }
  // 创建新会话时关闭文件预览面板
  closeFilePreview();
  emit("createConversation");
};

const handleClose = () => {
  emit("close");
};

const handleMinimize = () => {
  emit("minimize");
};

const handleOverlay = () => {
  emit("overlay", !props.isOverlay);
};

// 内部复制处理
const handleInternalCopy = async (
  rowtext: string | undefined,
  content: string | undefined,
  type: string,
) => {
  await copyToClipboard(content, {
    rawText: rowtext,
    isMobile: isMobile.value,
    onSuccess: () => {
      MessagePlugin.success(mergedChatI18n.value.copySuccess);
    },
    onError: () => {
      const text = mergedChatI18n.value.copyFailed;
      MessagePlugin.error(text);
      emit("message", MessageCode.COPY_FAILED, text);
    },
  });
  emit("copy", rowtext, content, type);
};

/**
 * 发送 widget_action SSE 请求
 * 从 handleInternalWidgetEvent 中提取的 SSE 通信逻辑
 */
const sendWidgetActionSSE = async (
  conversationId: string,
  applicationId: string,
  widgetAction: WidgetActionRequest,
) => {
  let streamConversationKey =
    conversationId ||
    currentConversationStateKey.value ||
    createPendingConversationKey();
  currentConversationStateKey.value = streamConversationKey;
  const streamState = ensureConversationRuntimeState(streamConversationKey);
  if (!streamState) return;

  streamState.isChatting = true;
  streamState.applicationId = applicationId || streamState.applicationId;
  mainLayoutRef.value?.getChatRef()?.setHasUserScrolled(false);

  const timestamp = Date.now();
  const baseExtraInfo = (isFromSelf: boolean) => ({
    RequestId: "",
    TraceId: "",
    Elapsed: 0,
    StartTime: timestamp,
    IsFromSelf: isFromSelf,
  });

  // 创建助手消息占位
  const assistantRecord: Record = {
    Role: "assistant",
    RecordId: "placeholder-agent",
    ConversationId: conversationId || streamConversationKey,
    Status: "processing",
    StatusDesc: "",
    Messages: [],
    ExtraInfo: baseExtraInfo(false),
  };
  streamState.records.push(assistantRecord);

  nextTick(() => {
    mainLayoutRef.value?.getChatRef()?.backToBottom();
  });

  streamState.abortController = new AbortController();

  const contents = [{ Type: "widget_action", WidgetAction: widgetAction }];

  await fetchSSE(
    () =>
      sendMessage(
        {
          Contents: contents,
          ConversationId: conversationId || undefined,
          ApplicationId: applicationId,
          Language: backendLanguage.value,
          CustomVariables: languageCustomVariables.value,
        },
        { signal: streamState.abortController?.signal },
        mergedApiDetailConfig.value.sendMessageApi,
      ),
    {
      success(sseEvent: SseEvent) {
        if (sseEvent.Type === "conversation") {
          upsertConversation(sseEvent.Payload);
          loadConversations();
          if (sseEvent.Payload.IsNewConversation) {
            const previousKey = streamConversationKey;
            streamConversationKey = moveConversationRuntimeState(
              previousKey,
              sseEvent.Payload.Id,
              sseEvent.Payload.ApplicationId || streamState.applicationId,
            );
            if (currentConversationStateKey.value === previousKey) {
              currentConversationStateKey.value = streamConversationKey;
            }
          }
          if (currentConversationStateKey.value === sseEvent.Payload.Id) {
            internalCurrentConversation.value = {
              ...(internalCurrentConversation.value || sseEvent.Payload),
              ...sseEvent.Payload,
            };
          }
          return;
        }

        const targetState = ensureConversationRuntimeState(
          streamConversationKey,
        );
        if (!targetState) return;

        const resolvedApplicationId =
          targetState.applicationId ||
          applicationId ||
          internalCurrentApplication.value?.ApplicationId;

        const replacePlaceholder = (
          placeholderId: string,
          next: Record,
        ): Record | undefined => {
          const placeholderIdx = targetState.records.findIndex(
            (item) => item.RecordId === placeholderId,
          );
          if (placeholderIdx !== -1) {
            targetState.records.splice(placeholderIdx, 1, next);
            return next;
          }
          return undefined;
        };

        const updateRecord = (next: Record, placeholderId: string): Record => {
          const idx = targetState.records.findIndex(
            (item) => item.RecordId === next.RecordId,
          );
          if (idx !== -1) {
            if (targetState.records[idx] !== undefined) {
              Object.assign(targetState.records[idx], next);
              return targetState.records[idx] as Record;
            }
            return next;
          }
          const replaced = replacePlaceholder(placeholderId, next);
          if (replaced) return replaced;
          targetState.records.push(next);
          return next;
        };

        // Widget action 的 request_ack 包含用户消息记录
        if (sseEvent.Type === "request_ack") {
          const nextUser = applySseEventToRecord(sseEvent, undefined);
          if (nextUser) {
            const placeholderIdx = targetState.records.findIndex(
              (item) => item.RecordId === "placeholder-agent",
            );
            if (placeholderIdx !== -1) {
              targetState.records.splice(placeholderIdx, 0, nextUser);
            } else {
              const lastIdx = targetState.records.length - 1;
              targetState.records.splice(lastIdx, 0, nextUser);
            }
          }
          return;
        } else {
          const lastIndex = targetState.records.length - 1;
          const lastRecord = targetState.records[lastIndex];
          const baseAssistant =
            lastRecord &&
            (lastRecord.RecordId === "placeholder-agent" ||
              lastRecord.Role === "assistant")
              ? lastRecord
              : undefined;
          const nextAssistant = applySseEventToRecord(sseEvent, baseAssistant);
          if (nextAssistant) {
            const appliedAssistant = updateRecord(
              nextAssistant,
              "placeholder-agent",
            );
            void hydrateReferences([appliedAssistant], {
              applicationId: resolvedApplicationId,
            });
          }
        }
      },
      complete(isOk) {
        const targetState =
          conversationRuntimeStates.value[streamConversationKey];
        if (targetState) {
          targetState.isChatting = false;
          targetState.abortController = null;
        }
        if (!isOk) {
          return;
        }
        if (currentConversationStateKey.value === streamConversationKey) {
          nextTick(() => {
            mainLayoutRef.value?.getChatRef()?.backToBottom();
          });
        }
      },
      fail(msg) {
        const failureText = handleStreamFailure(msg);
        if (failureText) {
          markLatestAssistantError(streamConversationKey, failureText);
        }
      },
    },
  );
};

// 内部 Widget 事件处理（API 模式）
const handleInternalWidgetEvent = async (
  event: CustomEvent,
  widgetRunId: string,
  widgetId: string,
  recordId: string,
) => {
  // 使用集中式事件处理器进行路由分发
  const result = routeWidgetEvent(event, widgetRunId, widgetId);

  // sys.go_to_url / sys.download 等本地处理完成的事件
  if (result.handled) {
    emit("widgetEvent", event, widgetRunId, widgetId, recordId);
    return;
  }

  // sys.chat / sys.clarify - 需要发送 SSE 请求
  if (result.widgetActionRequest) {
    // 检查是否正在进行请求
    const currentKey = currentConversationStateKey.value;
    if (currentKey && isConversationChatting(currentKey)) {
      console.warn("[layout/Index] widget action: 正在进行请求，跳过此次提交");
      if (recordId) {
        disableWidgetsByRecordId(recordId);
      }
      return;
    }

    // 先禁用该消息下的所有 widgets（防止重复提交）
    if (recordId) {
      disableWidgetsByRecordId(recordId);
    }

    if (!useApiMode.value) {
      emit("widgetEvent", event, widgetRunId, widgetId, recordId);
      return;
    }

    const conversationId =
      internalCurrentConversation.value?.Id ||
      currentConversationStateKey.value;
    const applicationId = internalCurrentApplication.value?.ApplicationId || "";

    if (!conversationId) {
      console.warn("[layout/Index] widget action: 没有当前会话");
      emit("widgetEvent", event, widgetRunId, widgetId, recordId);
      return;
    }

    // 发送 widget_action SSE 请求
    await sendWidgetActionSSE(
      conversationId,
      applicationId,
      result.widgetActionRequest,
    );

    emit("widgetEvent", event, widgetRunId, widgetId, recordId);
    return;
  }

  // 其他事件类型，只向外传递
  emit("widgetEvent", event, widgetRunId, widgetId, recordId);
};

// 内部文件上传处理（API 模式）
const handleInternalUploadFile = async (files: File[]) => {
  if (!useApiMode.value) {
    emit("uploadFile", files);
    return;
  }

  if (isUploading.value) return;

  isUploading.value = true;
  emit("uploadStatus", "uploading");

  const senderRef = mainLayoutRef.value?.getChatRef()?.getSenderRef();

  for (const file of files) {
    const uid = `${Date.now()}-${Math.random().toString(36).slice(2)}-${file.name}`;
    const category = file.type.startsWith("image/") ? "image" : "document";

    // 立即添加文件到列表，状态为 uploading，显示 loading
    if (senderRef) {
      senderRef.addFile({
        uid,
        name: file.name,
        url: "",
        size: file.size,
        type: file.type,
        category,
        status: "uploading",
      });
    }

    try {
      const response = await uploadFile(
        file,
        currentApplicationId.value,
        mergedApiDetailConfig.value.uploadApi,
        chatMode.value,
      );
      if (senderRef && response) {
        const fileUrl = response.Url || response.url;
        senderRef.updateFile(uid, {
          url: fileUrl,
          status: "done",
        });

        // standard 模式下，非图片文件需要调用实时文档解析获取 doc_id
        if (
          chatMode.value === "standard" &&
          category === "document" &&
          mergedApiDetailConfig.value.fileParseApi
        ) {
          const extName = file.name.split(".").pop() || "";
          try {
            const parseResult = await parseFile(
              {
                ApplicationId: currentApplicationId.value,
                FileName: file.name,
                FileType: extName,
                FileUrl: fileUrl,
                CosUrl: response.CosUrl || response.cos_url || "",
                CosBucket: response.CosBucket || response.cos_bucket || "",
                ETag: response.ETag || response.e_tag || "",
                CosHash: response.CosHash || response.cos_hash || "",
                Size: String(file.size || 0),
              },
              mergedApiDetailConfig.value.fileParseApi,
            );

            if (
              parseResult &&
              parseResult.doc_id &&
              parseResult.doc_id !== "0"
            ) {
              senderRef.updateFile(uid, { docId: parseResult.doc_id });
            }
          } catch (parseError) {
            console.warn("文档解析失败，将使用 FileUrl 模式:", parseError);
          }
        }
      }
    } catch (error) {
      if (senderRef) {
        senderRef.removeFile(uid);
      }
      const uploadErrorText = mergedSenderI18n.value.uploadError;
      MessagePlugin.error(uploadErrorText);
      emit("message", MessageCode.FILE_UPLOAD_FAILED, uploadErrorText);
    }
  }

  isUploading.value = false;
  emit("uploadStatus", "done");
  emit("uploadFile", files);
};

// 记录上一次的 ID 值，用于判断变化
let prevConvId: string | undefined = undefined;

// 监听外部传入的 currentApplicationId 和 currentConversationId 变化
watch(
  [
    () => props.currentApplicationId,
    () => props.currentConversationId,
    () => actualApplications.value,
    () => actualConversations.value,
  ],
  async ([appId, convId, apps, conversations]) => {
    // 处理应用 ID 变化
    if (appId && apps.length > 0) {
      const foundApp = apps.find((app) => app.ApplicationId === appId);
      if (
        foundApp &&
        foundApp.ApplicationId !==
          internalCurrentApplication.value?.ApplicationId
      ) {
        internalCurrentApplication.value = foundApp;
      }
    }

    // 处理会话 ID 变化
    if (convId && conversations.length > 0) {
      const foundConv = conversations.find((conv) => conv.Id === convId);
      if (
        foundConv &&
        (foundConv.Id !== internalCurrentConversation.value?.Id ||
          currentConversationStateKey.value !== foundConv.Id)
      ) {
        internalCurrentConversation.value = foundConv;
        currentConversationStateKey.value = foundConv.Id;
        setConversationApplicationId(foundConv.Id, foundConv.ApplicationId);
        // 如果会话有关联的应用，且未指定 appId，则自动切换应用
        if (!appId && foundConv.ApplicationId && apps.length > 0) {
          const convApp = apps.find(
            (app) => app.ApplicationId === foundConv.ApplicationId,
          );
          if (convApp) {
            internalCurrentApplication.value = convApp;
          }
        }
      }
    } else if (!convId && prevConvId) {
      // ID 从有值变为空时，清空当前会话
      internalCurrentConversation.value = undefined;
      currentConversationStateKey.value = "";
    }

    // 更新上一次的值
    prevConvId = convId;
  },
  { immediate: true },
);

// 监听外部传入的 currentApplication 对象变化，同步内部状态
watch(
  () => props.currentApplication,
  (newApp) => {
    if (newApp) {
      internalCurrentApplication.value = newApp;
    }
  },
  { immediate: true },
);

// 监听外部传入的 currentConversation 对象变化，同步内部状态
watch(
  [() => props.currentConversation, () => actualApplications.value],
  async ([newConversation, apps]) => {
    if (
      newConversation &&
      (newConversation.Id !== internalCurrentConversation.value?.Id ||
        currentConversationStateKey.value !== newConversation.Id)
    ) {
      internalCurrentConversation.value = newConversation;
      currentConversationStateKey.value = newConversation.Id;
      setConversationApplicationId(
        newConversation.Id,
        newConversation.ApplicationId,
      );
      // 同时更新对应的应用
      if (newConversation.ApplicationId && apps.length > 0) {
        const foundApp = apps.find(
          (app) => app.ApplicationId === newConversation.ApplicationId,
        );
        if (foundApp) {
          internalCurrentApplication.value = foundApp;
        }
      }
    }
  },
  { immediate: true },
);

// 组件挂载时自动加载数据
onMounted(async () => {
  if (useApiMode.value && props.autoLoad) {
    // axios 配置已由 useApiConfig composable 自动处理
    // 先加载用户信息和系统配置，因为如果配置了AUTO_CREATE_ACCOUNT，会在加载用户信息时创建账户
    await Promise.all([loadUserInfo(), loadSystemConfig()]);
    await Promise.all([loadApplications(), loadConversations()]);
  }
});

onUnmounted(() => {
  Object.values(conversationRuntimeStates.value).forEach((state) => {
    state.abortController?.abort();
    state.abortController = null;
    state.isChatting = false;
  });
});

// 暴露方法供外部调用
defineExpose({
  loadApplications,
  loadConversations,
  loadConversationDetail,
  loadUserInfo,
  loadSystemConfig,
  notifyLoaded: () => mainLayoutRef.value?.notifyLoaded(),
  notifyComplete: () => mainLayoutRef.value?.notifyComplete(),
  openFilePreview,
  closeFilePreview,
  getFilePreviewRef: () => filePreviewLayoutRef.value,
});
</script>

<template>
  <TLayout class="page-container">
    <TContent class="content">
      <!-- 移动端毛玻璃遮罩 -->
      <div
        v-if="isSidePanelOverlay && sidebarVisible"
        class="mobile-overlay"
        @click="handleToggleSidebar"
      ></div>
      <SideLayout
        :isMobile="isMobile"
        :visible="sidebarVisible"
        :applications="actualApplications"
        :currentApplicationId="currentApplicationId"
        :conversations="actualConversations"
        :currentConversationId="currentConversationId"
        :userAvatarUrl="actualUser?.avatarUrl"
        :userAvatarName="actualUser?.avatarName"
        :userName="actualUser?.name"
        :theme="theme"
        :languageOptions="languageOptions"
        :isSidePanelOverlay="isSidePanelOverlay"
        :maxAppLen="maxAppLen"
        :i18n="props.sideI18n"
        @toggleSidebar="handleToggleSidebar"
        @selectApplication="handleSelectApplication"
        @selectConversation="handleSelectConversation"
        @toggleTheme="emit('toggleTheme')"
        @changeLanguage="(key) => emit('changeLanguage', key)"
        @logout="emit('logout')"
        @userClick="emit('userClick')"
      >
        <template
          #sider-logo
          v-if="logoUrl || logoTitle || $slots['sider-logo']"
        >
          <slot name="sider-logo">
            <LogoArea
              v-if="logoUrl || logoTitle"
              :logoUrl="logoUrl"
              :title="logoTitle"
            />
          </slot>
        </template>
      </SideLayout>
      <MainLayout
        ref="mainLayoutRef"
        :currentApplicationAvatar="currentApplicationAvatar"
        :currentApplicationName="currentApplicationName"
        :currentApplicationGreeting="currentApplicationGreeting"
        :currentApplicationOpeningQuestions="currentApplicationOpeningQuestions"
        :currentApplicationId="currentApplicationId"
        :currentConversationTitle="currentConversationTitle"
        :chatId="currentConversationId"
        :chatList="actualChatList"
        :isChatting="actualIsChatting"
        :isMobile="isMobile"
        :theme="theme"
        :language="actualLanguageValue"
        :mode="chatMode"
        :chatbotConfig="activeChatbotConfig"
        :showSidebarToggle="!sidebarVisible"
        :aiWarningText="actualAiWarningText"
        :i18n="props.chatI18n"
        :chatItemI18n="props.chatItemI18n"
        :senderI18n="props.senderI18n"
        :useInternalRecord="useApiMode"
        :asrUrlApi="mergedApiDetailConfig.asrUrlApi"
        :asrFileApi="mergedApiDetailConfig.asrFileApi"
        :enableVoiceInput="enableVoiceInput"
        :enableFileUpload="enableFileUpload"
        :isUploading="isUploading"
        :isOverlay="props.isOverlay"
        :termsResolving="termsResolving"
        :termsAccepted="!termsGateEnabled || termsAccepted"
        :termsPromptKey="termsPromptKey"
        @toggleSidebar="handleToggleSidebar"
        @createConversation="handleCreateConversation"
        @close="handleClose"
        @acceptTerms="handleAcceptTerms"
        @declineTerms="handleDeclineTerms"
        @send="handleInternalSend"
        @recordAudio="handleInternalRecordAudio"
        @stop="handleInternalStop"
        @loadMore="handleInternalLoadMore"
        @rate="handleInternalRate"
        @share="handleInternalShare"
        @copy="handleInternalCopy"
        @uploadFile="handleInternalUploadFile"
        @uploadStatus="
          (status: 'uploading' | 'done') => emit('uploadStatus', status)
        "
        @startRecord="emit('startRecord')"
        @stopRecord="emit('stopRecord')"
        @message="
          (code: MessageCode, message: string) => emit('message', code, message)
        "
        @conversationChange="
          (conversationId: string) => emit('conversationChange', conversationId)
        "
        @widgetEvent="handleInternalWidgetEvent"
      >
        <template #header-actions>
          <Tooltip
            v-if="!props.isOverlay && !isMobile && chatMode !== 'standard'"
            :content="mergedFilePreviewI18n.openFileList"
            destroyOnClose
            showArrow
            theme="default"
          >
            <span class="open-file-list-btn" @click="toggleFilePreview">
              <CustomizedIcon name="open_file_list" :theme="theme" />
            </span>
          </Tooltip>
        </template>
        <template
          #header-overlay-content
          v-if="showOverlayButton || $slots['header-overlay-content']"
        >
          <slot name="header-overlay-content">
            <button
              type="button"
              class="header-minimize-btn"
              aria-label="Minimize chatbot"
              @click="handleMinimize"
            >
              <svg
                viewBox="0 0 24 24"
                focusable="false"
                role="img"
                aria-hidden="true"
              >
                <path d="M5 12h14" />
              </svg>
            </button>
            <CustomizedIcon
              class="header-overlay-icon"
              v-if="showOverlayButton"
              name="overlay"
              :theme="theme"
              @click="handleOverlay"
            />
          </slot>
        </template>
        <template
          #header-close-content
          v-if="showCloseButton || $slots['header-close-content']"
        >
          <slot name="header-close-content">
            <CustomizedIcon
              class="header-overlay-icon"
              v-if="showCloseButton"
              name="logout_close"
              :theme="theme"
              @click="handleClose"
            />
          </slot>
        </template>
      </MainLayout>
      <FilePreviewLayout
        ref="filePreviewLayoutRef"
        :visible="filePreviewVisible"
        :conversationId="currentConversationId"
        :applicationId="currentApplicationId"
        :i18n="mergedFilePreviewI18n"
        @close="closeFilePreview"
      />
    </TContent>
  </TLayout>
</template>

<style scoped>
.page-container {
  height: 100%;
  width: 100%;
}
.content {
  display: flex;
  height: 100%;
  width: 100%;
  position: relative;
}
/* 移动端毛玻璃遮罩 */
.mobile-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: var(--td-mask-disabled);
  backdrop-filter: blur(4px);
  -webkit-backdrop-filter: blur(4px);
  z-index: 99;
}
.header-minimize-btn,
.header-overlay-icon {
  margin-left: var(--td-size-4);
}

.header-minimize-btn {
  width: 28px;
  height: 28px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  border: 0;
  background: transparent;
  color: #fff;
  cursor: pointer;
  border-radius: var(--td-radius-default, 4px);
  transition:
    background-color 0.2s ease,
    color 0.2s ease;
}

.header-minimize-btn:hover {
  background-color: rgba(0, 0, 0, 0.04);
}

.header-minimize-btn:focus,
.header-minimize-btn:focus-visible,
.header-minimize-btn:active {
  outline: none;
  box-shadow: none;
}

.header-minimize-btn svg {
  width: 24px;
  height: 24px;
  stroke: currentColor;
  stroke-width: 2;
  stroke-linecap: round;
  fill: none;
}

.open-file-list-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  cursor: pointer;
  color: inherit;
  border-radius: var(--td-radius-default, 4px);
  transition: background-color 0.2s ease;
}

.open-file-list-btn:hover {
  background-color: rgba(0, 0, 0, 0.04);
}
</style>
