<!-- 控制尺寸、展开和收起 -->
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import MainApp from './components/layout/Index.vue';
import type { Application } from './model/application';
import type { ChatConversation, Record } from './model/chat-v2';
import type { FileProps } from './model/file';
import { ScoreValue } from './model/chat-v2';
import type { ApiConfig } from './service/api';
import { defaultApiDetailConfig } from './service/api';
import { getMessage, type MessageCode } from './model/messages';
import { normalizeWidth, normalizeHeight } from './utils/device';
import type { 
    LanguageOption, 
    UserInfo,
    SideI18n, 
    ChatI18n, 
    ChatItemI18n, 
    SenderI18n,
    ChatRelatedProps,
    OverlayProps
} from './model/type';
import { 
    defaultLanguageOptions,
    chatRelatedPropsDefaults,
    overlayPropsDefaults,
    getI18nByLanguage
} from './model/type';

const DEFAULT_LAUNCHER_ICON_ZH = 'https://carers-webchat.aienchat.com/avatar-zh-hk-v5.gif';
const DEFAULT_LAUNCHER_ICON_EN = 'https://carers-webchat.aienchat.com/avatar-en-us-v5.gif';
const DEFAULT_AI_WARNING_TEXT_ZH = '内容由AI生成，仅供参考';
const DEFAULT_AI_WARNING_TEXT_EN = 'Content is generated by AI and is for reference only';

interface Props extends ChatRelatedProps, OverlayProps {
    /** 挂载容器选择器 */
    container?: string;
    /** 是否显示关闭按钮 */
    showCloseButton?: boolean;
    /** 是否显示浮层切换按钮 */
    showOverlayButton?: boolean;
    /** 是否显示悬浮切换按钮 */
    showToggleButton?: boolean;
    /** 悬浮切换按钮图标 URL（支持 gif/png/webp/svg） */
    launcherIconUrl?: string;
    /** 悬浮切换按钮位置 */
    launcherPosition?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
    /** 悬浮切换按钮水平边距 */
    launcherOffsetX?: string | number;
    /** 悬浮切换按钮垂直边距 */
    launcherOffsetY?: string | number;
    /** 是否为浮层模式：true-使用 width/height 浮动在容器上，false-宽高100%撑满容器 */
    isOverlay?: boolean;
    /** 宽度（仅在 isOverlay 为 true 时生效） */
    width?: string | number;
    /** 高度（仅在 isOverlay 为 true 时生效） */
    height?: string | number;
    /** 应用列表 */
    applications?: Application[];
    /** 当前选中的应用 */
    currentApplication?: Application;
    /** 会话列表 */
    conversations?: ChatConversation[];
    /** 当前选中的会话 */
    currentConversation?: ChatConversation;
    /** 聊天消息列表 */
    chatList?: Record[];
    /** 是否正在聊天中 */
    isChatting?: boolean;
    /** 用户信息 */
    user?: UserInfo;
    /** 语言选项列表 */
    languageOptions?: LanguageOption[];
    /** Logo URL */
    logoUrl?: string;
    /** Logo 标题 */
    logoTitle?: string;
    /** 最大应用显示数量 */
    maxAppLen?: number;
    /** 浮层状态切换回调 */
    onOverlayChange?: (isOverlay: boolean) => void;
    /** 主题切换回调 */
    onToggleTheme?: () => void;
    /** 语言切换回调 */
    onChangeLanguage?: (key: string) => void;
    /** 是否展开面板 */
    isOpen?: boolean;
    /** 面板展开状态变化回调 */
    onOpenChange?: (isOpen: boolean) => void;
    /** AI警告文本 */
    aiWarningText?: string;
    /** 侧边栏国际化文本 */
    sideI18n?: SideI18n;
    /** 聊天国际化文本 */
    chatI18n?: ChatI18n;
    /** ChatItem 国际化文本 */
    chatItemI18n?: ChatItemI18n;
    /** Sender 国际化文本 */
    senderI18n?: SenderI18n;
    /** 是否启用语音输入 */
    enableVoiceInput?: boolean;
    /** 是否启用文件上传入口 */
    enableFileUpload?: boolean;
    /** API 配置 - 如果传入则使用 HTTP 请求获取数据 */
    apiConfig?: ApiConfig;
    /** 是否自动加载数据（仅在使用 apiConfig 时生效） */
    autoLoad?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
    ...chatRelatedPropsDefaults,
    ...overlayPropsDefaults,
    container: 'body',
    showCloseButton: true,
    showOverlayButton: true,
    isOverlay: false,
    width: 400,
    height: 640,
    applications: () => [],
    conversations: () => [],
    chatList: () => [],
    isChatting: false,
    user: () => ({}),
    languageOptions: () => defaultLanguageOptions,
    logoUrl: '',
    logoTitle: '',
    maxAppLen: 4,
    onOverlayChange: undefined,
    onToggleTheme: undefined,
    onChangeLanguage: undefined,
    isOpen: undefined,
    onOpenChange: undefined,
    showToggleButton: true,
    launcherIconUrl: DEFAULT_LAUNCHER_ICON_ZH,
    launcherPosition: 'bottom-right',
    launcherOffsetX: 18,
    launcherOffsetY: 18,
    aiWarningText: DEFAULT_AI_WARNING_TEXT_ZH,
    enableVoiceInput: true,
    enableFileUpload: true,
    apiConfig: () => ({ apiDetailConfig: defaultApiDetailConfig }),
    autoLoad: true,
});

const emit = defineEmits<{
    (e: 'selectApplication', app: Application): void;
    (e: 'selectConversation', conversation: ChatConversation): void;
    (e: 'createConversation'): void;
    (e: 'toggleTheme'): void;
    (e: 'changeLanguage', key: string): void;
    (e: 'logout'): void;
    (e: 'userClick'): void;
    (e: 'close'): void;
    (e: 'send', query: string, fileList: FileProps[], conversationId: string, applicationId: string): void;
    (e: 'stop'): void;
    (e: 'loadMore', conversationId: string, lastRecordId: string): void;
    (e: 'rate', conversationId: string, recordId: string, score: typeof ScoreValue[keyof typeof ScoreValue]): void;
    (e: 'share', conversationId: string, applicationId: string, recordIds: string[]): void;
    (e: 'copy', rowtext: string | undefined, content: string | undefined, type: string): void;
    (e: 'uploadFile', files: File[]): void;
    (e: 'startRecord'): void;
    (e: 'stopRecord'): void;
    (e: 'message', type: 'warning' | 'error' | 'info' | 'success', message: string): void;
    (e: 'conversationChange', conversationId: string): void;
    (e: 'dataLoaded', type: 'applications' | 'conversations' | 'chatList' | 'user' | 'systemConfig', data: any): void;
    (e: 'overlay', isOverlay: boolean): void;
    (e: 'openChange', open: boolean): void;
}>();

// 内部 open 状态，初始化时使用用户传入的值
const internalOpen = ref(props.isOpen ?? false);

// 内部 theme 状态（用于没有 onToggleTheme 回调时的内部切换）
const internalTheme = ref(props.theme ?? 'light');

// 内部 language 状态（用于没有 onChangeLanguage 回调时的内部切换）
const internalLanguage = ref(props.language ?? 'zh-CN');

// 监听 props.isOpen 变化，同步内部状态
watch(() => props.isOpen, (newVal) => {
    if (newVal !== undefined) {
        internalOpen.value = newVal;
    }
});

// 监听 props.theme 变化，同步内部状态
watch(() => props.theme, (newVal) => {
    if (newVal !== undefined) {
        internalTheme.value = newVal;
    }
});

// 监听 props.language 变化，同步内部状态
watch(() => props.language, (newVal) => {
    if (newVal !== undefined) {
        internalLanguage.value = newVal;
    }
});

// 计算实际的 open 状态 - 始终使用内部状态，因为 createApp 传入的 props 是静态的
const isOpen = computed(() => internalOpen.value);

// 设置 open 状态
const setOpen = (value: boolean) => {
    internalOpen.value = value;
    props.onOpenChange?.(value);
    emit('openChange', value);
};

// 计算浮层模式下的样式
const panelParkStyle = computed(() => {
    if (actualIsOverlay.value) {
        const width = typeof actualWidth.value === 'number' ? `${actualWidth.value}px` : actualWidth.value;
        const height = typeof actualHeight.value === 'number' ? `${actualHeight.value}px` : actualHeight.value;
        return {
            width,
            height
        };
    }
    return {};
});

const handleClose = () => {
    setOpen(false);
    emit('close');
};

const handleOverlay = (_isOverlay: boolean) => {
    emit('overlay', _isOverlay);
    props.onOverlayChange?.(_isOverlay);
};

const handleToggleTheme = () => {
    emit('toggleTheme');
    if (props.onToggleTheme) {
        props.onToggleTheme();
    } else {
        // 内部切换主题
        const newTheme = internalTheme.value === 'light' ? 'dark' : 'light';
        console.log('[handleToggleTheme] switching from', internalTheme.value, 'to', newTheme);
        internalTheme.value = newTheme;
        // 设置 container 元素的 theme-mode 属性，让 TDesign CSS 变量生效
        const containerEl = document.querySelector(props.container);
        if (containerEl) {
            containerEl.setAttribute('theme-mode', newTheme);
        }
    }
};

const handleChangeLanguage = (key: string) => {
    emit('changeLanguage', key);
    if (props.onChangeLanguage) {
        props.onChangeLanguage(key);
    } else {
        // 内部切换语言
        internalLanguage.value = key;
    }
};

const toCssSize = (value: string | number | undefined): string | undefined => {
    if (value === undefined || value === null || value === '') return undefined;
    return typeof value === 'number' ? `${value}px` : value;
};

// 计算属性 - 用于响应 props 变化（通过 update 方法更新时）
const actualContainer = computed(() => props.container);
const actualIsShowToggleButton = computed(() => props.showToggleButton);
const actualLauncherIconUrl = computed(() => {
    if (props.launcherIconUrl === DEFAULT_LAUNCHER_ICON_ZH && actualLanguage.value?.startsWith('en')) {
        return DEFAULT_LAUNCHER_ICON_EN;
    }
    return props.launcherIconUrl;
});
const actualLauncherStyle = computed(() => {
    const style: { [key: string]: string } = {};
    const position = props.launcherPosition || 'bottom-right';
    const offsetX = toCssSize(props.launcherOffsetX) || '18px';
    const offsetY = toCssSize(props.launcherOffsetY) || '18px';

    if (position.includes('top')) {
        style.top = offsetY;
        style.bottom = 'auto';
    } else {
        style.bottom = offsetY;
        style.top = 'auto';
    }

    if (position.includes('left')) {
        style.left = offsetX;
        style.right = 'auto';
    } else {
        style.right = offsetX;
        style.left = 'auto';
    }

    return style;
});
const actualIsOverlay = computed(() => props.isOverlay);
// 规范化宽高：超出屏幕时使用屏幕尺寸减去 padding * 2
const actualWidth = computed(() => actualIsOverlay.value ? normalizeWidth(props.width) : props.width);
const actualHeight = computed(() => actualIsOverlay.value ? normalizeHeight(props.height) : props.height);
const actualApplications = computed(() => props.applications);
const actualCurrentApplication = computed(() => props.currentApplication);
const actualConversations = computed(() => props.conversations);
const actualCurrentConversation = computed(() => props.currentConversation);
const actualChatList = computed(() => props.chatList);
const actualIsChatting = computed(() => props.isChatting);
const actualUser = computed(() => props.user);
// 如果有 onToggleTheme 回调，使用 props.theme；否则使用内部状态
const actualTheme = computed(() => {
    const result = props.onToggleTheme ? props.theme : internalTheme.value;
    console.log('[actualTheme] computed:', result, 'hasCallback:', !!props.onToggleTheme, 'internalTheme:', internalTheme.value);
    return result;
});
const actualLanguageOptions = computed(() => props.languageOptions);
const actualLanguage = computed(() => internalLanguage.value);
const actualIsSidePanelOverlay = computed(() => props.isSidePanelOverlay);
const actualLogoUrl = computed(() => props.logoUrl);
const actualLogoTitle = computed(() => props.logoTitle);
const actualMaxAppLen = computed(() => props.maxAppLen);
const actualIsShowCloseButton = computed(() => props.showCloseButton);
const actualIsshowOverlayButton = computed(() => props.showOverlayButton);
const actualAiWarningText = computed(() => {
    if (props.aiWarningText === DEFAULT_AI_WARNING_TEXT_ZH && actualLanguage.value?.startsWith('en')) {
        return DEFAULT_AI_WARNING_TEXT_EN;
    }
    return props.aiWarningText;
});

// 根据内部语言状态获取默认 i18n
const defaultI18n = computed(() => getI18nByLanguage(internalLanguage.value));
// 如果外部传入了 i18n，优先使用外部的；否则使用根据语言计算的默认值
const actualSideI18n = computed(() => props.sideI18n ?? defaultI18n.value.sideI18n);
const actualChatI18n = computed(() => props.chatI18n ?? defaultI18n.value.chatI18n);
const actualChatItemI18n = computed(() => props.chatItemI18n ?? defaultI18n.value.chatItemI18n);
const actualSenderI18n = computed(() => props.senderI18n ?? defaultI18n.value.senderI18n);

const actualApiConfig = computed(() => props.apiConfig);
const actualAutoLoad = computed(() => props.autoLoad);
</script>

<template>
    <Teleport to="body">
        <div
            v-if="actualIsShowToggleButton && !isOpen"
            class="toggle-btn"
            :style="actualLauncherStyle"
            @click="setOpen(true)"
        >
            <span
                class="toggle-btn__icon"
                :style="{ backgroundImage: `url('${actualLauncherIconUrl}')` }"
            ></span>
        </div>
    </Teleport>

    <Teleport :to="actualContainer" :disabled="!actualIsOverlay">
        <div v-show="isOpen" @keydown.esc="setOpen(false)" tabindex="0"
            :class="[{ 'panel-park--full': !actualIsOverlay, 'panel-park--overlay': actualIsOverlay }]"
            :style="actualIsOverlay ? panelParkStyle : {}">
            <MainApp 
                :applications="actualApplications"
                :currentApplication="actualCurrentApplication"
                :conversations="actualConversations"
                :currentConversation="actualCurrentConversation"
                :chatList="actualChatList"
                :isChatting="actualIsChatting"
                :user="actualUser"
                :theme="actualTheme"
                :language="actualLanguage"
                :languageOptions="actualLanguageOptions"
                :isOverlay="actualIsOverlay"
                :width="actualWidth"
                :height="actualHeight"
                :container="actualContainer"
                :isSidePanelOverlay="actualIsSidePanelOverlay"
                :logoUrl="actualLogoUrl"
                :logoTitle="actualLogoTitle"
                :maxAppLen="actualMaxAppLen"
                :showCloseButton="actualIsShowCloseButton"
                :showOverlayButton="actualIsshowOverlayButton"
                :aiWarningText="actualAiWarningText"
                :sideI18n="actualSideI18n"
                :chatI18n="actualChatI18n"
                :chatItemI18n="actualChatItemI18n"
                :senderI18n="actualSenderI18n"
                :enableVoiceInput="props.enableVoiceInput"
                :enableFileUpload="props.enableFileUpload"
                :apiConfig="actualApiConfig"
                :autoLoad="actualAutoLoad"
                @selectApplication="(app: Application) => emit('selectApplication', app)"
                @selectConversation="(conversation: ChatConversation) => emit('selectConversation', conversation)"
                @createConversation="emit('createConversation')"
                @toggleTheme="handleToggleTheme"
                @changeLanguage="handleChangeLanguage"
                @logout="emit('logout')"
                @userClick="emit('userClick')"
                @close="handleClose"
                @overlay="handleOverlay"
                @send="(query: string, fileList: FileProps[], conversationId: string, applicationId: string) => emit('send', query, fileList, conversationId, applicationId)"
                @stop="emit('stop')"
                @loadMore="(conversationId: string, lastRecordId: string) => emit('loadMore', conversationId, lastRecordId)"
                @rate="(conversationId: string, recordId: string, score: typeof ScoreValue[keyof typeof ScoreValue]) => emit('rate', conversationId, recordId, score)"
                @share="(conversationId: string, applicationId: string, recordIds: string[]) => emit('share', conversationId, applicationId, recordIds)"
                @copy="(rowtext: string | undefined, content: string | undefined, type: string) => emit('copy', rowtext, content, type)"
                @uploadFile="(files: File[]) => emit('uploadFile', files)"
                @startRecord="emit('startRecord')"
                @stopRecord="emit('stopRecord')"
                @message="(code: MessageCode, message: string) => emit('message', getMessage(code).type, message)"
                @conversationChange="(conversationId: string) => emit('conversationChange', conversationId)"
                @dataLoaded="(type: 'applications' | 'conversations' | 'chatList' | 'user' | 'systemConfig', data: any) => emit('dataLoaded', type, data)"
            >
                <template #sider-logo>
                    <slot name="sider-logo"></slot>
                </template>
            </MainApp>
        </div>
    </Teleport>
</template>

<!-- 全局样式 - 用于 Teleport 传送后的组件 -->
<style>
@import './styles/theme.css';
@import './styles/chat-overrides.css';

.t-chat.isChatting .t-chat__to-bottom::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: url('./assets/icons/loading.svg');
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  animation: rotate 2s linear infinite;
  z-index: 2;
  border-radius: 9999px;
}

@keyframes rotate {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>

<style scoped>
.content {
    display: flex;
}

.panel-close-btn {
    width: 32px;
    height: 32px;
    padding: 0;
    border-radius: 32px;
}

.panel-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.toggle-btn__icon{
    display: inline-block;
    height:100px;
    width: 100px;
    background-size: contain;
    background-position: center;
    background-repeat: no-repeat;
}

.toggle-btn {
    position: fixed;
    z-index: 999;
    margin: 0;
    width: 100px;
    height: 100px;
    cursor: pointer;
    border-radius: 100%;
    background-color: transparent;
    border: 0;
    box-shadow: none;
    user-select: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform 0.2s ease;
}

.toggle-btn:hover {
    transform: scale(1.04);
}

.panel-park {
    background: white;
    box-sizing: border-box;
    overflow: hidden;
}

.panel-park--full {
    width: 100%;
    height: 100%;
}

.panel-park--overlay {
    /* 宽高由 style 动态设置 */
    border-radius: 14px;
    box-shadow: 0 6px 28px rgba(79, 42, 18, 0.22);

    position: fixed;
    z-index: 999;
    bottom: 24px;
    right: 24px;
    margin: 0;
    background-color: #fff8e8;
    border: 1px solid #f6b36c;
    overflow: hidden;
}
</style>
